<?php


/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */
/**
 * Implements hook_preprocess_HOOK() for block templates.
 */

use Drupal\Core\Template\RenderWrapper;
use Drupal\Core\Template\Attribute;
use Drupal\Component\Utility\Html;
use Drupal\Component\Utility\Xss;
use Drupal\search\Form\SearchBlockForm;
use Drupal\Component\Utility\SafeMarkup;
use Drupal\Core\Form\FormStateInterface;
use Drupal\system\Form\ThemeSettingsForm;
use Drupal\file\Entity\File;
use Drupal\Core\Url;
use Drupal\file\Plugin\Core\Entity\FileInterface;
use Drupal\Core\Config\ConfigFactoryInterface;
  
/**
 * Implements hook_preprocess_page() for block templates.
 */

global $theme_name, $path_to_acadmix;
$theme_name = \Drupal::theme()->getActiveTheme()->getName();
$path_to_acadmix = drupal_get_path('theme', 'acadmix');





function acadmix_preprocess_block(&$variables) {
  switch ($variables['base_plugin_id']) {
    case 'system_branding_block':
      $variables['site_logo'] = '';
      if ($variables['content']['site_logo']['#access'] && $variables['content']['site_logo']['#uri']) {
        $variables['site_logo'] = str_replace('.svg', '.png', $variables['content']['site_logo']['#uri']);
      }
      $variables['site_logo_2'] = $base_url . $base_path . drupal_get_path('theme','acadmix') . '/img/iitb-dj_trans.png';
      break;

  }
}


